build and deploy for authd
flant/negentropy pull request #183
Opened 2021-07-30 12:09 UTC by savelyev-an

2021-07-30 12:16 UTC, tuchinsky approved these changes

2021-08-02 11:32 UTC, diafour requested changes

2021-08-02 11:32 UTC, diafour commented on authd/README.md
> +- binary needs configs at /etc/flant/negentropy/authd-conf.d (it is a folder)
```suggestion
- binary needs configs in /etc/flant/negentropy/authd-conf.d directory
```

2021-08-02 11:32 UTC, diafour commented on authd/README.md
> +- GO111MODULE=on go build -o /OPT/authd/bin/authd cmd/authd/main.go
```suggestion
- GO111MODULE=on go build -o /opt/authd/bin/authd cmd/authd/main.go
```

Why /OPT in uppercase?

2021-08-03 07:07 UTC, merged